name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions: read-all

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.81.0

jobs:
  fmt_lint:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version
      - name: rustfmt check
        run: cargo fmt --all -- --check
      - name: clippy check
        run: cargo clippy --workspace --all-targets -- -D warnings

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: fmt_lint
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: wasm32-unknown-unknown
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version
      - name: Cargo fetch
        run: cargo fetch --locked
      - name: WASM release build
        run: cargo wasm --locked
      - name: Tests
        run: cargo test -- --nocapture

  artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    needs: fmt_lint
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: wasm32-unknown-unknown
      - name: Install protoc
        run: |
            sudo apt-get update
            sudo apt-get install -y protobuf-compiler
            protoc --version
      - name: Install wasm-opt
        run: cargo install wasm-opt --locked
      - name: WASM release build
        run: RUSTFLAGS="-C link-arg=-s" cargo wasm --locked
      - name: Optimize WASM artifacts
        run: |
          mkdir artifacts
          for f in target/wasm32-unknown-unknown/release/*.wasm; do
              wasm-opt -Os "$f" -o "artifacts/$(basename "$f")"
          done
      - name: Generate checksums
        run: |
          cd artifacts
          sha256sum -- *.wasm | tee checksums.txt
      - name: Artifact (all targets)
        if: success()
        uses: actions/upload-artifact@v4
        with:
            name: converter-artifacts
            path: artifacts/*

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: fmt_lint
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: wasm32-unknown-unknown
      - name: Install protoc
        run: |
            sudo apt-get update
            sudo apt-get install -y protobuf-compiler
            protoc --version
      - name: Install cargo-tarpaulin
        run: cargo +1.82.0 install cargo-tarpaulin
      - name: Run coverage
        run: cargo +1.82.0 tarpaulin --workspace --all-features --all-targets --locked --out Xml --output-dir coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/cobertura.xml
          fail_ci_if_error: true
